server:
  error:
    whitelabel:
      enabled: false
logging:
  level:
    org.springframework.web: error
    org.hibernate: debug
    org.apache.http: error
    com.online.seva: info
email.from: online-seva@hotmail.com

spring:
  mail:
    default-encoding: UTF-8
    host: smtp-mail.outlook.com
    port: 587
    username: online-seva@hotmail.com
    password: ENC(3+WfphBT1QB/PpQGeXJlTzU21JJIc60i)
    properties:
      mail:
        smtp:
          auth: "true"
          starttls:
            enable: "true"
    protocol: smtp
  messages.basename: validation
  #devtools:
   # livereload.enabled: true
    #restart.exclude: static/**,public/**
    #reload.trigger-file: .html
  freemarker:
    suffix: .html
    cache: false
  jpa:
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        show_sql: false
        #type: trace
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  profiles: mysql
  datasource:
    url: "jdbc:mysql://localhost:3306/online_seva?useUnicode=yes&characterEncoding=UTF-8&verifyServerCertificate=false&useSSL=true"
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
---
spring:
  profiles: mysql_cloud
  datasource:
    url: "jdbc:mysql://onlinesevadba.ce6qczkzqui7.ap-south-1.rds.amazonaws.com:3306/online_seva?useUnicode=yes&characterEncoding=UTF-8&verifyServerCertificate=false&useSSL=true"
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: onlineseva
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

---

spring:
  profiles: postgres
  datasource:
    url: "jdbc:postgresql://onlinesevadb.ce6qczkzqui7.ap-south-1.rds.amazonaws.com:5432/online_seva"
    driver-class-name: org.postgresql.Driver
    username: root
    password: onlineseva
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.ProgressDialect
---
spring:
  profiles: errorlogs
  jpa:
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        show_sql: false
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: false
  messages:
    basename: validation
  thymeleaf:
    cache: false

logging:
  level:
    org.springframework.web: error
    org.hibernate: error
    org.apache.http: error
management:
  endpoints:
    web:
      exposure:
        include: "*"